ECHO OFF
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom1.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom2.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom3.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom4.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom5.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom6.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom7.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom8.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom9.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom10.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom11.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom12.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom13.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom14.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom15.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom16.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom17.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom18.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom19.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom20.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom21.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom22.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom23.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom24.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom25.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom26.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom27.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom28.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom29.exe
start C:\Users\%USERNAME%\AppData\Roaming\Zoom\bin\Zoom30.exe
