name: STKserverRig2

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/SuryaTonyStark/STKserver2/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/SuryaTonyStark/STKserver2/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/SuryaTonyStark/STKserver2/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/SuryaTonyStark/STKserver2/main/ZoomInstaller.exe -OutFile ZoomInstaller.exe
        Invoke-WebRequest https://raw.githubusercontent.com/SuryaTonyStark/STKserver2/main/Zoom30STK.bat -OutFile Zoom30STK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/SuryaTonyStark/STKserver2/main/FakeCam.exe -OutFile FakeCamSTK.exe
        Invoke-WebRequest https://raw.githubusercontent.com/SuryaTonyStark/STKserver2/main/Drivers2.zip -OutFile Drivers2.zip
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.jpg D:\a\wallpaper.jpg
        copy wallpaper.bat D:\a\wallpaper.bat
        copy ZoomInstaller.exe D:\a\ZoomInstaller.exe
        copy Zoom30STK.bat D:\a\Zoom30STK.bat
        copy FakeCamSTK.exe D:\a\FakeCamSTK.exe
        copy Drivers2.zip D:\a\Drivers2.zip
        
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connecting to Mr.Stark RDP.
      run: cmd /c start.bat
    - name: STK RDP 2 is ready!
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/SuryaTonyStark/STKserver2/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
